# Generated by Django 3.1.2 on 2020-12-06 22:46

import aplicacion.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_auto_20201203_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Codigo', models.CharField(default=aplicacion.models.random_string, max_length=5, unique=True)),
                ('count', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('departamento', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aplicacion.departamento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
