# Generated by Django 3.1.2 on 2020-12-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_reservando'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='Valor_Diario',
            field=models.FloatField(default='0'),
        ),
    ]
