# Generated by Django 3.1.2 on 2020-12-07 02:33

import aplicacion.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_auto_20201206_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservando',
            name='Codigo_Reservas',
            field=models.CharField(default=aplicacion.models.random_string, max_length=5, unique=True),
        ),
        migrations.AddField(
            model_name='reservando',
            name='Estado_Reservas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservando',
            name='Fecha_Reservas_Inicio',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reservando',
            name='Fecha_Reservas_Termino',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reservando',
            name='checks',
            field=models.CharField(default='No Check', max_length=100),
        ),
        migrations.AddField(
            model_name='reservando',
            name='servicioextra',
            field=models.ManyToManyField(blank=True, null=True, to='aplicacion.ServicioExtra'),
        ),
        migrations.AddField(
            model_name='reservando',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
