# Generated by Django 3.1.2 on 2020-12-07 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_auto_20201206_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservando',
            name='Codigo_Reservas',
        ),
    ]
