# Generated by Django 3.1.2 on 2020-12-07 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0015_auto_20201206_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservando',
            name='Fecha_Reserva_Inicios',
        ),
        migrations.RemoveField(
            model_name='reservando',
            name='Fecha_Reserva_Terminos',
        ),
        migrations.RemoveField(
            model_name='reservando',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='reservando',
            name='servicioextras',
        ),
    ]
