# Generated by Django 3.1.2 on 2020-12-07 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0016_auto_20201207_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservando',
            name='departamento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aplicacion.departamento'),
        ),
    ]
