# Generated by Django 3.1.2 on 2020-12-07 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0020_reservando_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservando',
            name='user',
        ),
    ]
