# Generated by Django 3.1.2 on 2020-12-07 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0022_auto_20201207_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservando',
            name='Fecha_Reserva_Inicios',
        ),
        migrations.RemoveField(
            model_name='reservando',
            name='Fecha_Reserva_Terminos',
        ),
    ]
