# Generated by Django 3.1.2 on 2020-12-08 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0026_auto_20201207_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservando',
            name='Fecha_Reserva_Inicios',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reservando',
            name='Fecha_Reserva_Terminos',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
