# Generated by Django 3.1.2 on 2020-12-08 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0028_auto_20201208_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservadetalle',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamento_venta', to='aplicacion.departamento'),
        ),
    ]
