# Generated by Django 3.1.2 on 2020-12-08 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0029_auto_20201208_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservando',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
