# Generated by Django 3.1.2 on 2020-12-08 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0030_reservando_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservando',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientela', to=settings.AUTH_USER_MODEL, verbose_name='cliente'),
        ),
    ]
