# Generated by Django 3.1.2 on 2020-12-08 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0033_auto_20201208_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservando',
            old_name='created_by',
            new_name='user',
        ),
    ]
