# Generated by Django 3.1.2 on 2020-12-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0034_auto_20201208_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservando',
            name='user',
        ),
    ]
