# Generated by Django 3.1.2 on 2020-12-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0035_remove_reservando_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservando',
            name='servicioextra',
            field=models.ManyToManyField(blank=True, null=True, to='aplicacion.ServicioExtra'),
        ),
    ]
